# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'nautisubs docker'
    repository: 'nautisubs/release'
    command: 'buildAndPush'
    Dockerfile: 'release/Dockerfile'
    buildContext: 'release'
    tags: 'latest'
